### ISSUE TITLE
Login Window Popping up on Grafana

### ISSUE THREAD

**Issue by Zhilei** [simonsobs/sisock#44]
When we were using Grafana to monitor the temperatures for a long period of time, say hours. Occasionally, the login window pops up.

Sometimes, we could log back in by just clicking the 'sign in' button while sometimes the window keeps coming up no matter how many times we click it. The only way to save that was to close the tab and restart everything again. I will be great if this can be fixed.

A screenshot of this is attached. Thanks a lot!
![Capture](https://user-images.githubusercontent.com/9847573/62883240-9988b100-bd01-11e9-8532-080c06696872.PNG)

**Comment by BrianJKoopman** [comment]
This is more to do with the web server setup than it is sisock, so I'm going to close this. I'm surprised asking your browser to "remember" things doesn't work. Probably we should work to improve the web server setup, like I recently did at UCSD.
