### ISSUE TITLE
Make OCS agents for sisock servers

### ISSUE THREAD

**Issue by ahincks** [simonsobs/sisock#6]
Sisock servers should be started/stopped/(monitored?) by OCS agents. We should add this functionality.

@BrianJKoopman, this might be a good project for me to do as it will get me up-to-speed on the OCS. But if it's something for some reason you'd like/need sooner rather than later and want to implement, let me know and you can go ahead.

**Comment by BrianJKoopman** [comment]
This issue is pretty stale at this point. Data servers are started/stopped by docker-compose. If other situations needs to be handled, a new issue should be opened, or this one should be reopened. Closing for now.
